# CH02-Tensors

tensor是一种数据结构，与numpy中的arrays和matrices类似。

在pytorch中，使用tensor作为模型的输入输出和模型参数。

区别于Numpy中arrays的是tensor可以运行在GPU上。但是它们可以共享内存数据（拷贝数据）


In [1]:
import torch
import numpy as np

## 1-初始化Tensor

有多种方式可以来初始化张量(Tensor)

### 1.1 from data

In [8]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)


### 1.2 from Numpy array

In [7]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### 1.3 from another tensor

In [6]:
# retains the properties of x_data
x_ones = torch.ones_like(x_data) 
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6370, 0.7342],
        [0.0528, 0.1552]]) 



### 1.4 使用随机值或常量值

生成固定维度的张量。

+ `torch.rand(shape)`

+ `torch.ones(shape)`

+ `torch.zeros(shape)`

In [9]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6998, 0.9427, 0.4681],
        [0.8462, 0.4973, 0.5688]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 2-Tensor属性

tensor具有3个属性：shape, datatype,device

+ tensor.shape

+ tensor.dtype

+ tensor.device

In [11]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


 ## 3-Tensor运算

tensor运算有100多种: [链接](https://pytorch.org/docs/stable/torch.html)

这些运算都可以在 GPU 上运行（速度通常比在 CPU 上更快）

默认情况下，张量是在 CPU 上创建的，我们需要使用`.to`方法明确地将张量移动到 GPU （在检查 GPU 可用性之后）

In [12]:
tensor = torch.rand(3,4)

# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')


### 3.1 索引和切片


In [13]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])

tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 3.2 连结

`torch.cat([tensor,tensor,tensor],dim=1)`

In [15]:
# 叠加列
t1 = torch.cat([tensor, tensor, tensor], dim=1)

print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### 3.3 算术运算

以下三种运算，结果相同。

In [16]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### 3.4 将tensor的单元素值，转为python数值

使用`.item()`

In [18]:
agg=tensor.sum()
print(agg)

agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


### 3.5 In-place operations

即：将运算结果，存储到操作数中的操作。使后缀`_`表示，比如：`x.copy_(y)`,将改变x.

**`inplace`操作节省了内存，但在计算导数时可能会出错，因为它会立即丢失历史记录。因此，不建议使用**

In [19]:
它print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## 4-桥接numpy

CPU 和 NumPy 数组上的张量可以共享它们的底层内存位置，改变一个将改变另一个。

### 4.1 tensor 到 numpy

`tensor.numpy()`

In [20]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


### 4.2 numpy 到 tensor

`torch.from_numpy()`

In [22]:
n = np.ones(5)
t = torch.from_numpy(n)

t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)